jobs:
- name: pipeline
  plan:
  - get: bucc-pipelines
    trigger: true
  - put: credhub
    params:
      schema_file: bucc-pipelines/concourse/schema.yml
  - put: concourse
    params:
      pipelines:
      - name: concourse-worker
        team: main
        config_file: bucc-pipelines/concourse/external-workers.yml

resources:
- name: bucc-pipelines
  type: git
  source:
    uri: "https://github.com/starkandwayne/bucc-pipelines"
    branch: base-pipeline

- name: credhub
  type: credhub-schema
  source:
    server: ((credhub_url))
    client_name: ((credhub_username))
    client_secret: ((credhub_password))
    ca_cert: ((credhub_ca_cert))
    path: /concourse/main/concourse-worker

- name: concourse
  type: concourse-pipeline
  source:
    target: ((concourse_url))
    insecure: "true"
    teams:
    - name: main
      username: ((concourse_username))
      password: ((concourse_password))

resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

- name: credhub-schema
  type: docker-image
  source:
    repository: rkoster/credhub-schema-resource
    tag: latest
