required:
- instances
- worker_vm_type
- external_worker_network_name
- worker_azs
- worker_tags
properties:
  instances:
    type: integer
    default: 1
  worker_vm_type:
    type: string
    default: default
  external_worker_network_name:
    type: string
    default: default
  worker_azs:
    type: object
    default:
      value: [z1, z2, z3]
    properties:
      value:
        type: array
        items:
          type: string
  worker_tags:
    type: object
    default:
      value: []
    properties:
      value:
        type: array
        items:
          type: string
