required:
- worker_instances
- worker_vm_type
- worker_network_name
- worker_azs
- worker_tags
properties:
  worker_instances:
    type: integer
    default: 1
  worker_vm_type:
    type: string
    default: default
  worker_network_name:
    type: string
    default: default
  worker_azs:
    type: object
    properties:
      value:
        type: array
        default: [z1, z2, z3]
        items:
          type: string
  worker_tags:
    type: object
    properties:
      value:
        type: array
        default: []
        items:
          type: string
