required:
- worker_instances
- worker_vm_type
- worker_network_name
properties:
  worker_instances:
    type: integer
    default: 1
  worker_vm_type:
    type: string
    default: default
  worker_network_name:
    type: string
    default: default
  worker_azs:
    type: object
    properties:
      value:
        type: array
        items:
          type: string
          default: [z1, z2, z3]
  worker_tags:
    type: object
    properties:
      value:
        type: array
        items:
          type: string
          default: []
