jobs:
- name: concourse_workers
  plan:
  - aggregate:
    - get: stemcell
    - get: concourse-deployment
    - get: bucc-pipelines
  - put: credhub
    params: { schema_file: bucc-pipelines/concourse-external-workers/bosh/schema.yml }
  - put: deploy
    params:
      manifest: concourse-deployment/cluster/external-worker.yml
      stemcells: [ stemcell/stemcell.tgz ]
      ops_files:
      - bucc-pipelines/concourse-external-workers/bosh/operations/absolute_concourse_creds.yml
      - bucc-pipelines/concourse-external-workers/bosh/operations/credhub_pseudo_array.yml
      vars:
        deployment_name: concourse_workers
        concourse_version: 3.8.0
        concourse_sha1: 99e134676df72e18c719ccfbd7977bd9449e6fd4
        garden_runc_version: 1.9.4
        garden_runc_sha1: 9cccd7685ac075ad6956cba3ab5881e3435cd7e3

resources:
- name: concourse-deployment
  type: git
  source:
    uri: https://github.com/concourse/concourse-deployment.git
    branch: master

- name: bucc-pipelines
  type: git
  source:
    uri: https://github.com/starkandwayne/bucc-pipelines.git

- name: stemcell
  type: bosh-io-stemcell
  source: { name: ((bosh_stemcell)) }

- name: deploy
  type: bosh-deployment
  source:
    deployment: concourse_workers
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))

- name: credhub
  type: credhub-schema
  source:
    server: ((credhub_url))
    client_name: ((credhub_username))
    client_secret: ((credhub_password))
    ca_cert: ((credhub_ca_cert))
    path: /((bosh_name))/concourse_workers

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest
- name: credhub-schema
  type: docker-image
  source:
    repository: rkoster/credhub-schema-resource
    tag: latest
